# Generated by Django 5.2.4 on 2025-09-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_alter_students_name_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='stid',
            field=models.CharField(unique=True),
        ),
    ]
